[project]
name = "py-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "litellm>=1.77.7",
    "parlant>=3.0.0",
]

[tool.uv]
required-environments = [
    "sys_platform == 'macosx_10_16_x86_64'",
]
